cluster_max_size: 1000
cluster_min_size: 25
cluster_tol: 0.02
plane_dist_thresh: 0.04
plane_max_iter: 100
ror_min_neighbors: 8
ror_radius_search: 0.010
voxel_leaf_size: 0.003
x_filter_max: 0.30
x_filter_min: -0.30
y_filter_max: 0.22
y_filter_min: -0.22
z_filter_max: 0.58
z_filter_min: 0.40
